// Code generated by go generate; DO NOT EDIT.
// This file was generated using data from https://api.kraken.com/0/public/Assets

package kraken

type Asset string

const (
	AAVE   Asset = "AAVE"
	ACA    Asset = "ACA"
	ADA    Asset = "ADA"
	ADAs   Asset = "ADA.S"
	ALGO   Asset = "ALGO"
	ALGOs  Asset = "ALGO.S"
	ANKR   Asset = "ANKR"
	ANT    Asset = "ANT"
	ASTR   Asset = "ASTR"
	ATLAS  Asset = "ATLAS"
	ATOM   Asset = "ATOM"
	ATOMs  Asset = "ATOM.S"
	AVAX   Asset = "AVAX"
	AXS    Asset = "AXS"
	BADGER Asset = "BADGER"
	BAL    Asset = "BAL"
	BAND   Asset = "BAND"
	BAT    Asset = "BAT"
	BCH    Asset = "BCH"
	BNC    Asset = "BNC"
	BNT    Asset = "BNT"
	CHF    Asset = "CHF"
	CHZ    Asset = "CHZ"
	COMP   Asset = "COMP"
	CQT    Asset = "CQT"
	CRV    Asset = "CRV"
	CTSI   Asset = "CTSI"
	DAI    Asset = "DAI"
	DASH   Asset = "DASH"
	DOT    Asset = "DOT"
	DOTp   Asset = "DOT.P"
	DOTs   Asset = "DOT.S"
	DYDX   Asset = "DYDX"
	ENJ    Asset = "ENJ"
	EOS    Asset = "EOS"
	ETH2   Asset = "ETH2"
	ETH2s  Asset = "ETH2.S"
	EURh   Asset = "EUR.HOLD"
	EURm   Asset = "EUR.M"
	EWT    Asset = "EWT"
	FIDA   Asset = "FIDA"
	FIL    Asset = "FIL"
	FLOW   Asset = "FLOW"
	FLOWs  Asset = "FLOW.S"
	FLOWH  Asset = "FLOWH"
	FLOWHs Asset = "FLOWH.S"
	GHST   Asset = "GHST"
	GLMR   Asset = "GLMR"
	GNO    Asset = "GNO"
	GRT    Asset = "GRT"
	ICX    Asset = "ICX"
	INJ    Asset = "INJ"
	KAR    Asset = "KAR"
	KAVA   Asset = "KAVA"
	KAVAs  Asset = "KAVA.S"
	KEEP   Asset = "KEEP"
	FEE    Asset = "KFEE"
	KILT   Asset = "KILT"
	KIN    Asset = "KIN"
	KINT   Asset = "KINT"
	KNC    Asset = "KNC"
	KSM    Asset = "KSM"
	KSMp   Asset = "KSM.P"
	KSMs   Asset = "KSM.S"
	LINK   Asset = "LINK"
	LPT    Asset = "LPT"
	LRC    Asset = "LRC"
	LSK    Asset = "LSK"
	LUNA   Asset = "LUNA"
	MANA   Asset = "MANA"
	MATIC  Asset = "MATIC"
	MINA   Asset = "MINA"
	MINAs  Asset = "MINA.S"
	MIR    Asset = "MIR"
	MKR    Asset = "MKR"
	MNGO   Asset = "MNGO"
	MOVR   Asset = "MOVR"
	NANO   Asset = "NANO"
	OCEAN  Asset = "OCEAN"
	OGN    Asset = "OGN"
	OMG    Asset = "OMG"
	ORCA   Asset = "ORCA"
	OXT    Asset = "OXT"
	OXY    Asset = "OXY"
	PAXG   Asset = "PAXG"
	PERP   Asset = "PERP"
	PHA    Asset = "PHA"
	POLIS  Asset = "POLIS"
	QTUM   Asset = "QTUM"
	RARI   Asset = "RARI"
	RAY    Asset = "RAY"
	REN    Asset = "REN"
	REPV2  Asset = "REPV2"
	SAND   Asset = "SAND"
	SBR    Asset = "SBR"
	SC     Asset = "SC"
	SDN    Asset = "SDN"
	SHIB   Asset = "SHIB"
	SNX    Asset = "SNX"
	SOL    Asset = "SOL"
	SOLs   Asset = "SOL.S"
	SRM    Asset = "SRM"
	STEP   Asset = "STEP"
	STORJ  Asset = "STORJ"
	SUSHI  Asset = "SUSHI"
	TBTC   Asset = "TBTC"
	TRX    Asset = "TRX"
	UNI    Asset = "UNI"
	USDh   Asset = "USD.HOLD"
	USDm   Asset = "USD.M"
	USDC   Asset = "USDC"
	USDT   Asset = "USDT"
	WAVES  Asset = "WAVES"
	WBTC   Asset = "WBTC"
	XBTm   Asset = "XBT.M"
	ETC    Asset = "XETC"
	ETH    Asset = "XETH"
	LTC    Asset = "XLTC"
	MLN    Asset = "XMLN"
	REP    Asset = "XREP"
	XTZ    Asset = "XTZ"
	XTZs   Asset = "XTZ.S"
	XBT    Asset = "XXBT"
	XDG    Asset = "XXDG"
	XLM    Asset = "XXLM"
	XMR    Asset = "XXMR"
	XRP    Asset = "XXRP"
	ZEC    Asset = "XZEC"
	YFI    Asset = "YFI"
	AUD    Asset = "ZAUD"
	CAD    Asset = "ZCAD"
	EUR    Asset = "ZEUR"
	GBP    Asset = "ZGBP"
	JPY    Asset = "ZJPY"
	ZRX    Asset = "ZRX"
	USD    Asset = "ZUSD"
)

type Assets struct {
	AAVE   float64 `json:"AAVE,string,omitempty"`
	ACA    float64 `json:"ACA,string,omitempty"`
	ADA    float64 `json:"ADA,string,omitempty"`
	ADAs   float64 `json:"ADA.S,string,omitempty"`
	ALGO   float64 `json:"ALGO,string,omitempty"`
	ALGOs  float64 `json:"ALGO.S,string,omitempty"`
	ANKR   float64 `json:"ANKR,string,omitempty"`
	ANT    float64 `json:"ANT,string,omitempty"`
	ASTR   float64 `json:"ASTR,string,omitempty"`
	ATLAS  float64 `json:"ATLAS,string,omitempty"`
	ATOM   float64 `json:"ATOM,string,omitempty"`
	ATOMs  float64 `json:"ATOM.S,string,omitempty"`
	AVAX   float64 `json:"AVAX,string,omitempty"`
	AXS    float64 `json:"AXS,string,omitempty"`
	BADGER float64 `json:"BADGER,string,omitempty"`
	BAL    float64 `json:"BAL,string,omitempty"`
	BAND   float64 `json:"BAND,string,omitempty"`
	BAT    float64 `json:"BAT,string,omitempty"`
	BCH    float64 `json:"BCH,string,omitempty"`
	BNC    float64 `json:"BNC,string,omitempty"`
	BNT    float64 `json:"BNT,string,omitempty"`
	CHF    float64 `json:"CHF,string,omitempty"`
	CHZ    float64 `json:"CHZ,string,omitempty"`
	COMP   float64 `json:"COMP,string,omitempty"`
	CQT    float64 `json:"CQT,string,omitempty"`
	CRV    float64 `json:"CRV,string,omitempty"`
	CTSI   float64 `json:"CTSI,string,omitempty"`
	DAI    float64 `json:"DAI,string,omitempty"`
	DASH   float64 `json:"DASH,string,omitempty"`
	DOT    float64 `json:"DOT,string,omitempty"`
	DOTp   float64 `json:"DOT.P,string,omitempty"`
	DOTs   float64 `json:"DOT.S,string,omitempty"`
	DYDX   float64 `json:"DYDX,string,omitempty"`
	ENJ    float64 `json:"ENJ,string,omitempty"`
	EOS    float64 `json:"EOS,string,omitempty"`
	ETH2   float64 `json:"ETH2,string,omitempty"`
	ETH2s  float64 `json:"ETH2.S,string,omitempty"`
	EURh   float64 `json:"EUR.HOLD,string,omitempty"`
	EURm   float64 `json:"EUR.M,string,omitempty"`
	EWT    float64 `json:"EWT,string,omitempty"`
	FIDA   float64 `json:"FIDA,string,omitempty"`
	FIL    float64 `json:"FIL,string,omitempty"`
	FLOW   float64 `json:"FLOW,string,omitempty"`
	FLOWs  float64 `json:"FLOW.S,string,omitempty"`
	FLOWH  float64 `json:"FLOWH,string,omitempty"`
	FLOWHs float64 `json:"FLOWH.S,string,omitempty"`
	GHST   float64 `json:"GHST,string,omitempty"`
	GLMR   float64 `json:"GLMR,string,omitempty"`
	GNO    float64 `json:"GNO,string,omitempty"`
	GRT    float64 `json:"GRT,string,omitempty"`
	ICX    float64 `json:"ICX,string,omitempty"`
	INJ    float64 `json:"INJ,string,omitempty"`
	KAR    float64 `json:"KAR,string,omitempty"`
	KAVA   float64 `json:"KAVA,string,omitempty"`
	KAVAs  float64 `json:"KAVA.S,string,omitempty"`
	KEEP   float64 `json:"KEEP,string,omitempty"`
	FEE    float64 `json:"KFEE,string,omitempty"`
	KILT   float64 `json:"KILT,string,omitempty"`
	KIN    float64 `json:"KIN,string,omitempty"`
	KINT   float64 `json:"KINT,string,omitempty"`
	KNC    float64 `json:"KNC,string,omitempty"`
	KSM    float64 `json:"KSM,string,omitempty"`
	KSMp   float64 `json:"KSM.P,string,omitempty"`
	KSMs   float64 `json:"KSM.S,string,omitempty"`
	LINK   float64 `json:"LINK,string,omitempty"`
	LPT    float64 `json:"LPT,string,omitempty"`
	LRC    float64 `json:"LRC,string,omitempty"`
	LSK    float64 `json:"LSK,string,omitempty"`
	LUNA   float64 `json:"LUNA,string,omitempty"`
	MANA   float64 `json:"MANA,string,omitempty"`
	MATIC  float64 `json:"MATIC,string,omitempty"`
	MINA   float64 `json:"MINA,string,omitempty"`
	MINAs  float64 `json:"MINA.S,string,omitempty"`
	MIR    float64 `json:"MIR,string,omitempty"`
	MKR    float64 `json:"MKR,string,omitempty"`
	MNGO   float64 `json:"MNGO,string,omitempty"`
	MOVR   float64 `json:"MOVR,string,omitempty"`
	NANO   float64 `json:"NANO,string,omitempty"`
	OCEAN  float64 `json:"OCEAN,string,omitempty"`
	OGN    float64 `json:"OGN,string,omitempty"`
	OMG    float64 `json:"OMG,string,omitempty"`
	ORCA   float64 `json:"ORCA,string,omitempty"`
	OXT    float64 `json:"OXT,string,omitempty"`
	OXY    float64 `json:"OXY,string,omitempty"`
	PAXG   float64 `json:"PAXG,string,omitempty"`
	PERP   float64 `json:"PERP,string,omitempty"`
	PHA    float64 `json:"PHA,string,omitempty"`
	POLIS  float64 `json:"POLIS,string,omitempty"`
	QTUM   float64 `json:"QTUM,string,omitempty"`
	RARI   float64 `json:"RARI,string,omitempty"`
	RAY    float64 `json:"RAY,string,omitempty"`
	REN    float64 `json:"REN,string,omitempty"`
	REPV2  float64 `json:"REPV2,string,omitempty"`
	SAND   float64 `json:"SAND,string,omitempty"`
	SBR    float64 `json:"SBR,string,omitempty"`
	SC     float64 `json:"SC,string,omitempty"`
	SDN    float64 `json:"SDN,string,omitempty"`
	SHIB   float64 `json:"SHIB,string,omitempty"`
	SNX    float64 `json:"SNX,string,omitempty"`
	SOL    float64 `json:"SOL,string,omitempty"`
	SOLs   float64 `json:"SOL.S,string,omitempty"`
	SRM    float64 `json:"SRM,string,omitempty"`
	STEP   float64 `json:"STEP,string,omitempty"`
	STORJ  float64 `json:"STORJ,string,omitempty"`
	SUSHI  float64 `json:"SUSHI,string,omitempty"`
	TBTC   float64 `json:"TBTC,string,omitempty"`
	TRX    float64 `json:"TRX,string,omitempty"`
	UNI    float64 `json:"UNI,string,omitempty"`
	USDh   float64 `json:"USD.HOLD,string,omitempty"`
	USDm   float64 `json:"USD.M,string,omitempty"`
	USDC   float64 `json:"USDC,string,omitempty"`
	USDT   float64 `json:"USDT,string,omitempty"`
	WAVES  float64 `json:"WAVES,string,omitempty"`
	WBTC   float64 `json:"WBTC,string,omitempty"`
	XBTm   float64 `json:"XBT.M,string,omitempty"`
	ETC    float64 `json:"XETC,string,omitempty"`
	ETH    float64 `json:"XETH,string,omitempty"`
	LTC    float64 `json:"XLTC,string,omitempty"`
	MLN    float64 `json:"XMLN,string,omitempty"`
	REP    float64 `json:"XREP,string,omitempty"`
	XTZ    float64 `json:"XTZ,string,omitempty"`
	XTZs   float64 `json:"XTZ.S,string,omitempty"`
	XBT    float64 `json:"XXBT,string,omitempty"`
	XDG    float64 `json:"XXDG,string,omitempty"`
	XLM    float64 `json:"XXLM,string,omitempty"`
	XMR    float64 `json:"XXMR,string,omitempty"`
	XRP    float64 `json:"XXRP,string,omitempty"`
	ZEC    float64 `json:"XZEC,string,omitempty"`
	YFI    float64 `json:"YFI,string,omitempty"`
	AUD    float64 `json:"ZAUD,string,omitempty"`
	CAD    float64 `json:"ZCAD,string,omitempty"`
	EUR    float64 `json:"ZEUR,string,omitempty"`
	GBP    float64 `json:"ZGBP,string,omitempty"`
	JPY    float64 `json:"ZJPY,string,omitempty"`
	ZRX    float64 `json:"ZRX,string,omitempty"`
	USD    float64 `json:"ZUSD,string,omitempty"`
}
