//go:build tools
// +build tools

package main

import "text/template"

// Template of the generated file
var packageTemplateAsset = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated using data from {{ .URL }}

package kraken

type Asset string

const (
{{- range $key, $value := .Assets }}
	{{ $value.Altname }} Asset = "{{ $key }}"
{{- end }}
)

type Assets struct {
{{- range $key, $value := .Assets }}
	{{ $value.Altname }} float64 ` + "`" + `json:"{{ $key }},string,omitempty"` + "`" + `
{{- end }}
}
`))

var packageTemplateAssetPairs = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated using data from {{ .URL }}

package kraken

type AssetPair string

const (
{{- range $key, $value := .AssetPairs }}
	{{ $value.WSname }} AssetPair = "{{ $key }}"
{{- end }}
)
`))
